In [1]:
import pandas as pd
import sqlite3

In [2]:
conn = sqlite3.connect(
    "../database/nifty100.db"
)

print("Database Connected")

Database Connected

In [3]:
companies = pd.read_csv(
    "../data/processed/companies_clean.csv"
)

analysis = pd.read_csv(
    "../data/processed/analysis_clean.csv"
)

balancesheet = pd.read_csv(
    "../data/processed/balancesheet_clean.csv"
)

cashflow = pd.read_csv(
    "../data/processed/cashflow_clean.csv"
)

profitandloss = pd.read_csv(
    "../data/processed/profitandloss_clean.csv"
)

documents = pd.read_csv(
    "../data/processed/documents_clean.csv"
)

prosandcons = pd.read_csv(
    "../data/processed/prosandcons_clean.csv"
)

print("Files Loaded")

Files Loaded

In [4]:
companies.to_sql(
    "companies",
    conn,
    if_exists="replace",
    index=False
)

analysis.to_sql(
    "analysis",
    conn,
    if_exists="replace",
    index=False
)

balancesheet.to_sql(
    "balancesheet",
    conn,
    if_exists="replace",
    index=False
)

cashflow.to_sql(
    "cashflow",
    conn,
    if_exists="replace",
    index=False
)

profitandloss.to_sql(
    "profitandloss",
    conn,
    if_exists="replace",
    index=False
)

documents.to_sql(
    "documents",
    conn,
    if_exists="replace",
    index=False
)

prosandcons.to_sql(
    "prosandcons",
    conn,
    if_exists="replace",
    index=False
)

print("Tables Created")

Tables Created

In [5]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table'
"""

pd.read_sql(query, conn)

            name
0      companies
1       analysis
2   balancesheet
3       cashflow
4  profitandloss
5      documents
6    prosandcons

In [6]:
query = """
SELECT COUNT(*) AS total_companies
FROM companies
"""

pd.read_sql(query, conn)

   total_companies
0               93

In [7]:
query = """
SELECT *
FROM companies
LIMIT 10
"""

pd.read_sql(query, conn)

,mkt_fintech_—_nifty_100__|__companies__|__92_records,unnamed:_1,unnamed:_2,unnamed:_3,unnamed:_4,unnamed:_5,unnamed:_6,unnamed:_7,unnamed:_8,unnamed:_9,unnamed:_10,unnamed:_11
0,id,company_logo,company_name,chart_link,about_company,website,nse_profile,bse_profile,face_value,book_value,roce_percentage,roe_percentage
1,ABB,https://mkt.in/static/mkt-icons/nifty100/ABB.png,Abbott India Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Abbott India Ltd is one of the leading multina...,https://www.abbott.co.in/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/abb...,10,1657,46,34.9
2,ADANIENSOL,https://m.economictimes.com/thumb/msid-1173715...,Adani Energy Solutions Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"AESL, part of the Adani portfolio, is a multid...",https://www.adanienergysolutions.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10,175,9,8.59
3,ADANIENT,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Enterprises Ltd,https://in.tradingview.com/chart/?symbol=ADANIENT,Adani Enterprises Ltd is an Indian multination...,https://www.adanienterprises.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,1,363,11.6,13.64
4,ADANIGREEN,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Green Energy Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"Adani Green Energy Limited, incorporated in 20...",http://www.adanigreenenergy.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10,67,96.5,14.7
5,ADANIPORTS,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Ports & Special Economic Zone Ltd\n,https://in.tradingview.com/chart/?symbol=NSE%3...,Adani Ports & Special Economic Zone is in the ...,http://www.adaniports.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,2,265,12.9,18.1
6,ADANIPOWER,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Power Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"Adani Power (APL), a part of the diversified A...",http://www.adani.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10,145,32.2,57.1
7,AMBUJACEM,https://mkt.in/static/mkt-icons/nifty100/AMBUJ...,Ambuja Cements Ltd,https://in.tradingview.com/chart/qGsydD2w/?sym...,Ambuja Cements Ltd. is among the leading cemen...,https://www.ambujacement.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/amb...,2,205,12.8,9.24
8,APOLLOHOSP,https://mkt.in/static/mkt-icons/nifty100/APOLL...,Apollo Hospitals\nChain of Indian private hosp...,https://in.tradingview.com/chart/?symbol=NSE%3...,Apollo Hospitals Enterprise Limited is an Indi...,https://www.apollohospitals.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/apo...,5,522,17.2,13.81
9,ASIANPAINT,https://mkt.in/static/mkt-icons/nifty100/ASIAN...,Asian Paints\nIndian Multi-National Paint and ...,https://in.tradingview.com/chart/?symbol=NSE%3...,Asian Paints Ltd is an Indian multinational pa...,https://www.asianpaints.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/asi...,1,188,41.75,31.45

In [8]:
query = """
SELECT COUNT(*) AS total_records
FROM profitandloss
"""

pd.read_sql(query, conn)

   total_records
0           1277

In [9]:
query = """
SELECT COUNT(*) AS total_records
FROM cashflow
"""

pd.read_sql(query, conn)

   total_records
0           1188

In [10]:
query = """
SELECT COUNT(*) AS total_records
FROM balancesheet
"""

pd.read_sql(query, conn)

   total_records
0           1313

In [11]:
conn.commit()

print("Database Saved")

Database Saved

In [12]:
conn.close()

print("Connection Closed")

Connection Closed